
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: spring-boot-demo

custom:
  thread-pool:
    core-pool-size: 5
    max-pool-size: 10
    # 默认为秒
    keep-alive-seconds: 60
    queue-capacity: 100
    thread-name-prefix: lantin-testThread-

