server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: spring-boot-demo
  #  mvc:
  #    format:
  #      date-time: yyyy-MM-dd HH:mm:ss
  #      date: yyyy-MM-dd HH:mm:ss
  # mysql数据源相关配置 type配置不同的数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #   Jedis： Java实现的直连客户端 阻塞IO 同步调用，spring2.以后默认使用lettuce客户端
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    connect-timeout: 2000
    timeout: 10000
    database: 0
    # 以下是对lettuce，客户端连接池的配置
    lettuce:
      pool:
        # 连接池最大连接数(使用负值表示没有限制) 默认为8
        max-active: 8
        # 连接池最大的阻塞等待时间，默认-1，为没有限制
        max-wait: -1
        # 连接池中的最大空闲连接 默认为8
        max-idle: 8
        # 连接池中的最小空闲连接 默认为8
        min-idle: 0
redisson:
  address: redis://127.0.0.1:6379
  connect-timeout: 2000
  timeout: 10000
  password: 123456
  database: 1

lantin:
  framework:
    swagger2:
      base-package: com.lantin.springboot.controller
  thread-pool:
    core-pool-size: 5
    max-pool-size: 10
    # 默认为秒
    keep-alive-seconds: 60
    queue-capacity: 100
    thread-name-prefix: lantin-testThread-


